# vim:set ft=tmux:
%hidden MODULE_NAME="load"

set -ogq "@themux_${MODULE_NAME}_icon" "󰊚"
set -ogq "@themux_${MODULE_NAME}_color" "#{E:@thm_blue}"
set -ogq "@themux_${MODULE_NAME}_text" "#(uptime | awk '{split(substr($0, index($0, \"load\")), a, \":\"); print a[2]}')"

source -F "#{d:current_file}/../utils/module_block.conf"
