# vim:set ft=tmux:
%hidden MODULE_NAME="time"

# Clock-only counterpart to date_time: just the time, no date.
set -ogq "@themux_${MODULE_NAME}_icon" ""
set -ogq "@themux_${MODULE_NAME}_color" "#{E:@thm_sky}"
set -ogq "@themux_${MODULE_NAME}_text" "%H:%M"

source -F "#{d:current_file}/../utils/module_block.conf"
