# vim:set ft=tmux:
%hidden MODULE_NAME="uptime"

set -ogq @themux_${MODULE_NAME}_icon "󰔟 "
set -ogq @themux_${MODULE_NAME}_color "#{E:@thm_sapphire}"
set -ogq @themux_${MODULE_NAME}_text "#(uptime | sed 's/^[^,]*up *//; s/, *[[:digit:]]* user.*//; s/ day.*, */d /; s/ hr\\(s*\\).*/h/; s/ min\\(s*\\).*/m/; s/ sec\\(s*\\).*/s/; s/\\([0-9]\\{1,2\\}\\):\\([0-9]\\{1,2\\}\\)/\\1h \\2m/;')"

source -F "#{d:current_file}/../utils/module_block.conf"
