blank_issues_enabled: false
contact_links:
  - name: Get Support
    url: https://github.com/jals1212/themux/discussions/new?category=help
    about: Need help configuring themux? Ask questions in GitHub Discussions!
  - name: Show & Tell
    url: https://github.com/jals1212/themux/discussions/new?category=show-tell
    about: Want to showcase your themux setup? Show it off in GitHub Discussions!
