# vim:set ft=tmux:

# Naked panes: plain borders on the default (transparent) background.
set -wgF pane-border-style "bg=default,fg=#{@thm_surface_0}"
set -wgF pane-active-border-style "bg=default,fg=#{@thm_overlay_0}"
