# vim:set ft=tmux:

# Slanted caps for the optional pane status; everything else is
# the squared variant.
set -ogq @themux_pane_left_separator ""
set -ogq @themux_pane_right_separator ""

source -F "#{d:current_file}/squared.conf"
