# vim:set ft=tmux:

# Squared blocks for the optional pane status.
set -ogq @themux_pane_left_border "█"
set -ogq @themux_pane_right_border "█"

source -F "#{d:current_file}/../../utils/panes_block.conf"
