# vim:set ft=tmux:

# Computes @_tmx_w_flags from @themux_window_flags. Callers unset it when
# they are done building the window formats.
%if "#{==:#{@themux_window_flags},icon}"
  set -gqF @_tmx_w_flags "#{E:@themux_window_flags_icon_format}"
%elif "#{==:#{@themux_window_flags},text}"
  set -gq @_tmx_w_flags "#F"
%else
  set -gq @_tmx_w_flags ""
%endif
