# vim:set ft=tmux:

  set -gq @themux_window_left_separator "#[fg=#{@_tmx_status_bg},reverse]#[none]"
  set -gq @themux_window_middle_separator " "
  set -gq @themux_window_right_separator "#[fg=#{@_tmx_status_bg},reverse]#[none]"

source -F "#{d:current_file}/../../utils/window_block.conf"
