# vim:set ft=tmux:

# Squared windows: solid blocks separated by spaces.
set -gq @themux_window_left_separator " "
set -gq @themux_window_middle_separator " "
set -gq @themux_window_right_separator " "

source -F "#{d:current_file}/../../utils/window_block.conf"
