# vim:set ft=tmux:

  set -gq @themux_window_left_separator " "
  set -gq @themux_window_middle_separator " "
  set -gq @themux_window_right_separator " "

source -F "#{d:current_file}/../../utils/window_block.conf"
